window.H5_CONFIG = {
  apiUrl: "https://wnsyh2026.socialmedia-fanchi.com/api/submit",
  activity: {
    title: "跟着麦穗儿，发现不止一面的渭南",
    subtitle: "八个点位，八段故事，等你亲自抵达",
    date: "2026.08.15—2026.09.30",
  },
  assets: {
    home: "assets/pages/p1-home.jpg",
    overview: "assets/pages/p2-overview.jpg",
    prize: "assets/pages/p4-entry.jpg",
    form: "assets/pages/p5-form.jpg",
  },
  spots: [
    {
      id: "huashan",
      name: "华山",
      keyword: "华",
      hook: "一朵从石头里开出的花",
      route: "山河东线",
      asset: "assets/spots/01-huashan.jpg",
    },
    {
      id: "cangjiemiao",
      name: "仓颉庙",
      keyword: "字",
      hook: "从一枚汉字，回到文明的来处",
      route: "文明非遗线",
      asset: "assets/spots/02-cangjiemiao.jpg",
    },
    {
      id: "qiachuan",
      name: "合阳洽川",
      keyword: "情",
      hook: "在河洲边，遇见诗经里的心动",
      route: "黄河人文线",
      asset: "assets/spots/03-qiachuan.jpg",
    },
    {
      id: "hancheng",
      name: "韩城古城",
      keyword: "史",
      hook: "走进一部还在继续的史书",
      route: "黄河人文线",
      asset: "assets/spots/04-hancheng.jpg",
    },
    {
      id: "tongguan",
      name: "潼关",
      keyword: "关",
      hook: "山与河共同写成的一道关",
      route: "山河东线",
      asset: "assets/spots/05-tongguan.jpg",
    },
    {
      id: "fengtuyicang",
      name: "丰图义仓",
      keyword: "粮",
      hook: "丰年里，也要记得荒年",
      route: "黄河人文线",
      asset: "assets/spots/06-fengtuyicang.jpg",
    },
    {
      id: "yaotouyao",
      name: "澄城尧头窑",
      keyword: "火",
      hook: "泥土经过火，就有了新的名字",
      route: "文明非遗线",
      asset: "assets/spots/07-yaotouyao.jpg",
    },
    {
      id: "laojie",
      name: "渭南老街",
      keyword: "家",
      hook: "新街里的旧乡音",
      route: "山河东线",
      asset: "assets/spots/08-laojie.jpg",
    },
  ],
};
