window.H5_CONFIG = {
  cloudbaseEnvId: "weinan-h5-2026-d7g0bsxva8f547fe5",
  cloudbaseSubmitFunction: "submitActivity",
  cloudbaseVisitFunction: "recordVisit",
  apiBase: "https://weinan-h5-2026-d7g0bsxva8f547fe5-1427680283.ap-shanghai.app.tcloudbase.com",
  uploadTokenPath: "/api/upload-token",
  submitPath: "/api/submit",
  visitPath: "/api/visit",
  visitRefreshInterval: 12 * 1000,
  // 示例照片可持续追加，前端不设数量上限。例如：["assets/gallery/001.webp", "assets/gallery/002.webp"]
  galleryPhotos: [],
  activity: {
    title: "6000年渭南一朵 Hua",
    subtitle: "循着一朵花，读懂渭南与华夏文明",
    date: "2026.08.15—2026.09.30",
  },
  assets: {
    home: "assets/pages/p1-home.webp?v=20260812b",
    homePetals: "assets/pages/p1-petals.webp?v=20260812b",
    homeTourButton: "assets/pages/p1-button-tour.webp?v=20260807i",
    homePrizeButton: "assets/pages/p1-button-prize.webp?v=20260807i",
    overview: "assets/pages/p2-overview.webp?v=20260812b",
    detailCheckinButton: "assets/buttons/detail/checkin.webp?v=20260810c",
    detailBackButton: "assets/buttons/detail/back.webp?v=20260810c",
    prize: "assets/pages/p4-entry.webp?v=20260812b",
    prizePhotoButton: "assets/buttons/p4-photo.png?v=20260810a",
    prizeSocialButton: "assets/buttons/p4-social.png?v=20260810a",
    form: "assets/pages/p5-form.webp?v=20260812b",
    formSubmitButton: "assets/buttons/p5-submit.png?v=20260810a",
  },
  spots: [
    {
      id: "huashan",
      name: "华山",
      keyword: "华",
      hook: "一朵从石头里开出的花",
      story: [
        "“自古华山一条路”“奇险天下第一”这是大多数游客对它的印象。但是，华山为什么叫“华山”呢？在古汉字里，“华”字通“花”，华山也因远望如一朵石花而得名。而“华夏”方始源自于“华山”这个“华”字，寄托了古代人民，对民族繁盛如花、繁荣兴茂的美好意愿。",
        "六千年前，距华山约29公里的泉护村，先民把“花瓣纹”画在大大小小的陶盆上，成为了仰韶文化最重要的代表之一。1965年，考古学家苏秉琦写下“华山玫瑰燕山龙”，刻在陶盆上的史前之花，成为华夏民族早期统一社会的象征。民族的意念，可能早已经开在渭南先民的花纹里。",
      ],
      route: "山河东线",
      asset: "assets/details/01-huashan.webp?v=20260810c",
      buttonAsset: "assets/buttons/spots/01-huashan.webp?v=20260807i",
      navigation: { name: "华山风景名胜区", longitude: 110.070978, latitude: 34.493336 },
    },
    {
      id: "cangjiemiao",
      name: "仓颉庙",
      keyword: "字",
      hook: "从一枚汉字，回到文明的来处",
      story: [
        "如果没有文字，现在的我们会是什么样子？相传仓颉是黄帝的史官，数千年前就已论证是渭南白水县人，他观察鸟兽走过的脚印，领悟到不同纹理可以相互区别的道理，从而创造出了文字。中华文字，来源于先祖对自然万物的细致观察，也体现了华夏民族的伟大智慧。",
        "中国的甲骨文，是世界古典文字中，唯一绵延流传至今的文字，也是现代汉字的鼻祖。甲骨文字是中华先民留下的最宝贵的财富，当我们写下“人”“山”“水”“雨”仍然能够追溯，几千年前祖先画在龟甲上的刻痕。如果不信，来这里，写几笔试试？",
      ],
      route: "文明非遗线",
      asset: "assets/details/02-cangjiemiao.webp?v=20260810c",
      buttonAsset: "assets/buttons/spots/02-cangjiemiao.webp?v=20260807i",
      navigation: { name: "仓颉庙", longitude: 109.651119, latitude: 35.103987 },
    },
    {
      id: "qiachuan",
      name: "洽川景区",
      keyword: "情",
      hook: "在河洲边，遇见诗经里的心动",
      story: [
        "关关雎鸠，在河之洲，窈窕淑女，君子好逑。这朗朗上口的2句话，只要中国人就一定会背。但是“河之洲”究竟是哪里？象征爱情的雎鸠，又在哪里和鸣呢？3000年前，采诗官走过渭南合阳县位于洽川的黄河湿地，这首来自民间的情歌，从此收进了中国第一部诗集。这就是《诗经》的起源。",
        "我们从不知道，《关雎》正是《诗经》里的第一篇诗集。作为一首情歌，孔子对它的评价极高：关雎，风之始也，所以风天下而正夫妇也。自古以来，夫妇关系是人伦之始，男女情感是风化起源。情感的心动，建立了整个社会的风化秩序。爱情的伟大，流传千年。",
      ],
      route: "黄河人文线",
      asset: "assets/details/03-qiachuan.webp?v=20260810c",
      buttonAsset: "assets/buttons/spots/03-qiachuan.webp?v=20260807i",
      navigation: { name: "洽川风景名胜区", longitude: 110.245912, latitude: 35.184502 },
    },
    {
      id: "hancheng",
      name: "韩城",
      keyword: "史",
      hook: "走进一部还在继续的史书",
      story: [
        "司马迁（公元前145-公元前90年）冯翊夏阳（今渭南韩城）人。自幼饱读诗书，立志撰史，哪怕是触怒汉武帝、忍辱负重、仍然坚持大志。《史记》历经16年艰辛终成，成为华夏文明最重要的记忆，也是世界史学的珍宝。西晋年间，古人为司马迁建祠，延续1700年，成为民族的精神地标。",
        "《史记》对于民族传承的作用，远远超过一本史书作品。它构建了中华民族的“起源叙事”，建立了民族共同体的认同作用，建立了“正统”的历史标准。是中华民族自我认知的奠基，也是民族文化认同的记忆图谱。如果说汉字让中华民族“形传”3000年，那么《史记》则让中华民族“魂续”3000年。",
      ],
      route: "黄河人文线",
      asset: "assets/details/04-hancheng.webp?v=20260810c",
      buttonAsset: "assets/buttons/spots/04-hancheng.webp?v=20260807i",
      navigation: { name: "司马迁祠景区", longitude: 110.413465, latitude: 35.374889 },
    },
    {
      id: "tongguan",
      name: "潼关",
      keyword: "关",
      hook: "山与河共同写成的一道关",
      story: [
        "你可能还记得：“山河表里潼关路”南倚秦岭，北临黄河，潼关自古就是关中通往中原的咽喉要塞。东汉建安16年（公元211年），曹操在这里设立关卡，抵御西凉马超，直到1945年抗战胜利，潼关防线保持完整，外敌仍然无法打下这座城堡。大风在这里吹了1700年时间，站上城头，你才能懂得什么是“一夫当关，万夫莫开”。",
        "除了语文书上的名词名句，在守卫中原的1700年期间，潼关一共打了82场战事。无论胜败，这座城隘之下，埋藏着多少战士的尸骨。“山河表里潼关路”后半句是什么？“兴，百姓苦；亡，百姓苦。”潼关不仅见证着战事，也见证古时关中人民的艰难生存，与强大的意志魄力。",
      ],
      route: "山河东线",
      asset: "assets/details/05-tongguan.webp?v=20260810c",
      buttonAsset: "assets/buttons/spots/05-tongguan.webp?v=20260807i",
      navigation: { name: "潼关古城", longitude: 110.292811, latitude: 34.605159 },
    },
    {
      id: "fengtuyicang",
      name: "丰图义仓",
      keyword: "粮",
      hook: "丰年里，也要记得荒年",
      story: [
        "“天下第一仓”“清代粮仓”这是大多数人对它的印象。但是，丰图义仓为什么叫“丰图义仓”呢？“丰图”二字，取“丰亨豫大”之意，又含“丰年储粮、图谋久远”之愿；“义仓”则是中国古代民间共筹、灾年赈济的公共粮仓。这个名字，寄托了古代人民的美好意愿，丰衣足食、守望相助。",
        "一百多年前，清光绪八年，朝邑人阎敬铭在黄河岸边筑起这座仓城。此后每逢灾年，它便开仓放粮，救民无数。从老官台的粟种到“天下第一仓”，渭南的黄土里长着八千年农耕根脉。世界三大农业起源中心之一，一粒种子曾改变过东方文明的走向。装的不只是粮食，是农业大市的底气，是中国人的热肠。",
      ],
      route: "黄河人文线",
      asset: "assets/details/06-fengtuyicang.webp?v=20260810c",
      buttonAsset: "assets/buttons/spots/06-fengtuyicang.webp?v=20260807i",
      navigation: { name: "丰图义仓", longitude: 110.092797, latitude: 34.796918 },
    },
    {
      id: "yaotouyao",
      name: "尧头窑",
      keyword: "火",
      hook: "泥土经过火，就有了新的名字",
      story: [
        "尧头窑烧的，不是专供宫廷赏玩的名瓷。它烧的是缸、盆、碗、罐，烧的是寻常百姓每天要用的器物。当地的土、煤与窑火相遇，烧出深沉的黑釉；火候稍有不同，釉色与纹理便各不相同。经过72道工序，器物才从泥土里站起来。尧头窑最珍贵的，正是这份粗朴而真实的烟火气。",
        "五千年前，华州泉护村，先民把信仰抟成雄鹰，铸成陶鹰鼎；一千多年后，同一片黄土地上，尧头窑的匠人烧碗、烧瓮、烧缸，为日子塑形。2006年，尧头窑陶瓷烧制技艺，列入首批国家级非物质文化遗产。从神性礼器到民生器用，从庙堂到灶间，渭南的窑火从未熄灭。",
      ],
      route: "文明非遗线",
      asset: "assets/details/07-yaotouyao.webp?v=20260810c",
      buttonAsset: "assets/buttons/spots/07-yaotouyao.webp?v=20260807i",
      navigation: { name: "尧头窑文化旅游生态园区", longitude: 109.932348, latitude: 35.184092 },
    },
    {
      id: "laojie",
      name: "渭南老街",
      keyword: "家",
      hook: "新街里的旧乡音",
      story: [
        "你是不是也跟我一样一听到老街，以为它的建筑年龄超高？希望你别被“老街”骗了：首先，老街“不老”，是近几年建设的新中式街区；其次，老街很“老”，秦腔、面花、皮影和各县小吃，却都是渭南的老味道；更甚，老街很“潮”，非遗文创、潮流文玩，统统都在这段小街道里。听我的，赶紧来打卡吧！",
        "老街的价值，不在“仿古”，而是在给旧生活提供一个新容器。城市可以更新，记忆却不必退场；当秦腔仍有人听、面花仍有人做，皮影还有人看，乡味仍有人尝，传统不再只是过去，渭南非遗，正在从所未有的速度，重新绽放全新的芳华！",
      ],
      route: "山河东线",
      asset: "assets/details/08-laojie.webp?v=20260810c",
      buttonAsset: "assets/buttons/spots/08-laojie.webp?v=20260807i",
      navigation: { name: "渭南老街", longitude: 109.480971, latitude: 34.483444 },
    },
  ],
};
